---
version: "3.7"
services:
  fastapi-web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi-web-app
    restart: unless-stopped
    volumes:
      - ./app/:/app:ro
    network_mode: "host"